[package]
name = "bakedpdf"
version = "0.1.0"
authors = ["Krzysztof Mędrzycki <aiwenari@gmail.com>"]

[dependencies]
env_logger = "0.5.10"
futures-await = "0.1.1"
lapin-futures = "0.12.0"
log = "0.4.2"
structopt = "0.2.10"
tokio = "0.1.7"
